### ISSUE TITLE
Do not work with sfdx-cli/7.123.1

### ISSUE THREAD

**Issue by jairzh** [ChuckJonas/force-source-clean#27]
Got the following error after run the `sfdx force:source:clean -n` command:

```
ERROR running force:source:retrieve:  XXX.cls-meta.xml: Expected source files for type 'ApexClass'
```

**Comment by ChuckJonas** [comment]
We keep the metadata files because if they are removed, static resources do not come back. At least this used to be the case.  Should retest this as maybe the underlying issue was resolved and we can start removing them again.

If that is still a problem, then maybe we only keep them for certain types.

https://github.com/callawaycloud/force-source-clean/issues/3

**Comment by ralphcallaway** [comment]
this currently works with 7.106.3, versions after that it starts erroring

current approach is 1) wipe meta files, 2) tag files with DELETE, 3) refresh. After 7.106.3 sfdx generates errors when refreshing a folder that has an NAME.cls but doesn't have NAME.cls-meta.xml (there are likely other file types)

should be able to deal with this by tagging meta files with delete so they're preserved before the refresh
